@startuml
title Monolith - Komponenten

() "HTTP:80" as http1

[Client - Browser] as client
rectangle "Docker-Dienste" {
	node "Monolith" as monolith {
		package "Web-Server mit App-Logik" as webserver {
			[Demo-API] as api
		}
		[Datenbank - sqlite in-memory] as db
	}
	note top of monolith
		diesen Rest unseres Monolithen
		lassen wir mal so unverbunden
		stehen - dazu kommen wir später
	endnote

	node "Feedback-Dienst" as feedback {
		() "HTTP:80" as http2
		package "Webserver" as feedback_webserver {
			[Form-backend] as form_backend
		}

	}
	node "Frontend-Service" as frontend {
		package "Webserver" as front_webserver {
			[statische Seiten] as static_site
			[Site-Builder] as site_builder
			[HTTP-Proxy] as proxy
		}

	}
}


[Email-Dienst (extern)] as email
[mkdocs-Dokumentation] as doc

http1 -- front_webserver
http2 -- feedback_webserver

client ..> http1
proxy .right.> http2
client ..> doc
api ..> db: fragt ab
form_backend ..> email: sendet
site_builder .up.> static_site: liefert
@enduml