
# nginx.conf:
worker_processes  auto;

http {
    upstream mywebapp {
        server server1;
        server server2;
        server server3;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://mywebapp;
        }
    }
}
events {
    worker_connections  1024;
}

