@startuml
title Monolith - Komponenten

[Client - Browser] as client
node "Monolith" as monolith {
	package "Web-Server mit App-Logik" as webserver {
		[statische Seiten] as static_site
		[Form-backend] as form_backend
		[Demo-API] as api
	}
	[Datenbank - sqlite in-memory] as db
}
[Site-Builder] as site_builder

[Email-Dienst (extern)] as email
[mkdocs-Dokumentation] as doc
HTTP -- webserver
client ..> HTTP: Ruft auf
client ..> doc: Ruft auf
api ..> db: fragt ab
form_backend ..> email: sendet
site_builder .left.> static_site: liefert
@enduml

