@startuml
title Microservice - Komponenten

() "HTTP:80" as http_webserver
() "HTTP:80" as http_api

[Client - Browser] as client
rectangle "Docker-Dienste" {
	rectangle #ccffee {
		node "API-Service" as api_service {
			() "HTTP:3000" as http_api_int
			package "Web-Server mit App-Logik" as api_server {
				[Demo-API] as api
			}
			[Datenbank - sqlite in-memory] as db
		}

	}

	node "Feedback-Dienst" as feedback {
		() "HTTP:3000" as http2
		package "Webserver" as feedback_webserver {
			[Form-backend] as form_backend
		}

	}
	node "Frontend-Service" as frontend {
		package "Webserver" as front_webserver {
			[statische Seiten] as static_site
			[Site-Builder] as site_builder
			[HTTP-Proxy] as proxy
		}

	}
}


[Email-Dienst (extern)] as email
[mkdocs-Dokumentation] as doc

http_webserver -- front_webserver
http2 - feedback_webserver
http_api_int - api_server

api ..> db: fragt ab

client ..> http_webserver
proxy ..> http2
proxy ..> http_api_int
client ..> doc
form_backend ..> email: sendet
site_builder .up.> static_site: liefert
@enduml